#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=tk
export VERSION=${VERSION:-8.6.7}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-tcl}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps tcl      || installpkg $PKGSTORE/tcl/tcl-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11   || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXau   || installpkg $PKGSTORE/x/libXau-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXdmcp || installpkg $PKGSTORE/x/libXdmcp-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxcb   || installpkg $PKGSTORE/x/libxcb-*.t?z || exit 99 ; }

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
