#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gnutls
export VERSION=${VERSION:-3.6.0}
export BUILD=${BUILD:-1}
#export BUILD=${BUILD:-1_slack14.2}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps guile           || installpkg $PKGSTORE/d/guile-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps gc              || installpkg $PKGSTORE/l/gc-[0-9]*.t?z      || exit 99; }
{ slackcheckpkgdeps gmp             || installpkg $PKGSTORE/l/gmp-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libidn2         || installpkg $PKGSTORE/l/libidn2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libunistring    || installpkg $PKGSTORE/l/libunistring-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps nettle          || installpkg $PKGSTORE/n/nettle-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps p11-kit         || installpkg $PKGSTORE/n/p11-kit-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG

