#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=mutt
export VERSION=${VERSION:-1.8.3}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps gdbm            || installpkg $PKGSTORE/l/gdbm-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps libidn          || installpkg $PKGSTORE/l/libidn-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps ncurses         || installpkg $PKGSTORE/l/ncurses-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps cyrus-sasl      || installpkg $PKGSTORE/n/cyrus-sasl-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps gpgme           || installpkg $PKGSTORE/n/gpgme-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libgpg-error    || installpkg $PKGSTORE/n/libgpg-error-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps openssl         || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
