#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=xfce4-settings
export VERSION=${VERSION:-4.12.1}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-xfce}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps dbus            || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps cairo           || installpkg $PKGSTORE/l/cairo-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps dbus-glib       || installpkg $PKGSTORE/l/dbus-glib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps gdk-pixbuf2     || installpkg $PKGSTORE/l/gdk-pixbuf2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps gtk+2           || installpkg $PKGSTORE/l/gtk+2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libnotify       || installpkg $PKGSTORE/l/libnotify-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxklavier     || installpkg $PKGSTORE/l/libxklavier-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps pango           || installpkg $PKGSTORE/l/pango-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps fontconfig      || installpkg $PKGSTORE/x/fontconfig-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXcursor      || installpkg $PKGSTORE/x/libXcursor-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXi           || installpkg $PKGSTORE/x/libXi-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libXrandr       || installpkg $PKGSTORE/x/libXrandr-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps exo             || installpkg $PKGSTORE/xfce/exo-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps garcon          || installpkg $PKGSTORE/xfce/garcon-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxfce4ui      || installpkg $PKGSTORE/xfce/libxfce4ui-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxfce4util    || installpkg $PKGSTORE/xfce/libxfce4util-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps xfconf          || installpkg $PKGSTORE/xfce/xfconf-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
