#!/bin/bash

source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=vorbis-tools
export PKGSERIES=ap
export VERSION=1.4.0
export BUILD=1
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure build dependencies:
{ slackcheckpkgdeps flac        || installpkg $PKGSTORE/ap/flac-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libao       || installpkg $PKGSTORE/l/libao-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libidn      || installpkg $PKGSTORE/l/libidn-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libogg      || installpkg $PKGSTORE/l/libogg-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libvorbis   || installpkg $PKGSTORE/l/libvorbis-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps curl        || installpkg $PKGSTORE/n/curl-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps openssl     || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
