#!/bin/bash

source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=libao
export PKGSERIES=l
export VERSION=1.2.2
export BUILD=1
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure additional dependencies:
{ slackcheckpkgdeps flac            || installpkg $PKGSTORE/ap/flac-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps alsa-lib        || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps audiofile       || installpkg $PKGSTORE/l/audiofile-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps esound          || installpkg $PKGSTORE/l/esound-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libogg          || installpkg $PKGSTORE/l/libogg-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps pulseaudio      || installpkg $PKGSTORE/l/pulseaudio-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
