#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gv
export VERSION=3.7.4
export BUILD=1
export PKGSERIES=xap
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# When I build X for ARMedslack, I removepkg it and rm -rf /usr/X11 which also
# removes xaw3d.  This way we remove the package from /var/log/packages and 
# we let slackcheckpkgdeps fix it below.
# I don't do that anymore with modular xorg.
#removepkg xaw3d
{ slackcheckpkgdeps libICE          || installpkg $PKGSTORE/x/libICE-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libSM           || installpkg $PKGSTORE/x/libSM-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXaw3d        || installpkg $PKGSTORE/x/libXaw3d-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXext         || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXinerama     || installpkg $PKGSTORE/x/libXinerama-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXmu          || installpkg $PKGSTORE/x/libXmu-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXpm          || installpkg $PKGSTORE/x/libXpm-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXt           || installpkg $PKGSTORE/x/libXt-[0-9]*.t?z   || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG 
