#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh
export PKGNAM=eudev
export VERSION=${VERSION:-3.2.2}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-a}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Run time dependencies:
{ slackcheckpkgdeps kmod        || installpkg $PKGSTORE/a/kmod-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps util-linux  || installpkg $PKGSTORE/a/util-linux-[0-9]*.t?z || exit 99; }
# Needed at build time:
{ slackcheckpkgdeps gperf       || installpkg $PKGSTORE/d/gperf-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
