#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=NetworkManager
export VERSION=${VERSION:-1.8.2}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps dbus            || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps eudev            || installpkg $PKGSTORE/a/eudev-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps util-linux      || installpkg $PKGSTORE/a/util-linux-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps xz              || installpkg $PKGSTORE/a/xz-[0-9]*.t?z      || exit 99; }
{ slackcheckpkgdeps sqlite          || installpkg $PKGSTORE/ap/sqlite-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps dbus-glib       || installpkg $PKGSTORE/l/dbus-glib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libnl3          || installpkg $PKGSTORE/l/libnl3-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libsoup         || installpkg $PKGSTORE/l/libsoup-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxml2         || installpkg $PKGSTORE/l/libxml2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps mozilla-nss     || installpkg $PKGSTORE/l/mozilla-nss-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps polkit          || installpkg $PKGSTORE/l/polkit-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps ModemManager    || installpkg $PKGSTORE/n/ModemManager-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
