#!/bin/bash

source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=python
export VERSION=${VERSION:-2.7.13}
export BUILD=${BUILD:-1}
#export BUILD=${BUILD:-1_slack14.2}
export PKGSERIES=${PKGSERIES:-d}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were:
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure build dependencies are satisfied:
{ slackcheckpkgdeps bzip2           || installpkg $PKGSTORE/a/bzip2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps sqlite          || installpkg $PKGSTORE/ap/sqlite-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps db44            || installpkg $PKGSTORE/l/db44-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps gdbm            || installpkg $PKGSTORE/l/gdbm-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps ncurses         || installpkg $PKGSTORE/l/ncurses-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps readline        || installpkg $PKGSTORE/l/readline-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps openssl         || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99; }
# Python 2.3 can be built without these because ARMedslack's original Python
# package was compiled long before any of these 4 packages were, but I'm
# adding them as dependencies now because Slackware's d/python package
# links against them:
{ slackcheckpkgdeps tcl             || installpkg $PKGSTORE/tcl/tcl-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps tk              || installpkg $PKGSTORE/tcl/tk-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
