#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gst-plugins-base
export VERSION=${VERSION:-1.12.2}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
# We need gtk-doc from linuxdoc-tools:
{ slackcheckpkgdeps linuxdoc-tools || installpkg $PKGSTORE/ap/linuxdoc-tools-*.t?z || exit 99 ; }
{ slackcheckpkgdeps cdparanoia  || installpkg $PKGSTORE/ap/cdparanoia-*.t?z || exit 99 ; }
{ slackcheckpkgdeps alsa-lib    || installpkg $PKGSTORE/l/alsa-lib-*.t?z || exit 99 ; }
{ slackcheckpkgdeps expat       || installpkg $PKGSTORE/l/expat-*.t?z || exit 99 ; }
{ slackcheckpkgdeps freetype    || installpkg $PKGSTORE/l/freetype-*.t?z || exit 99 ; }
{ slackcheckpkgdeps glib2       || installpkg $PKGSTORE/l/glib2-*.t?z || exit 99 ; }
{ slackcheckpkgdeps gstreamer   || installpkg $PKGSTORE/l/gstreamer-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libogg      || installpkg $PKGSTORE/l/libogg-*.t?z || exit 99 ; }
{ slackcheckpkgdeps liboil      || installpkg $PKGSTORE/l/liboil-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libtheora   || installpkg $PKGSTORE/l/libtheora-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libvisual   || installpkg $PKGSTORE/l/libvisual-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libvorbis   || installpkg $PKGSTORE/l/libvorbis-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxml2     || installpkg $PKGSTORE/l/libxml2-*.t?z || exit 99 ; }
{ slackcheckpkgdeps pango       || installpkg $PKGSTORE/l/pango-*.t?z || exit 99 ; }
{ slackcheckpkgdeps fontconfig  || installpkg $PKGSTORE/x/fontconfig-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libICE      || installpkg $PKGSTORE/x/libICE-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libSM       || installpkg $PKGSTORE/x/libSM-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXv       || installpkg $PKGSTORE/x/libXv-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
