#!/bin/bash

# gkrellm.SlackBuild
# Heavily based on the original Slackware build scripts,
# Modified by Stuart Winter <mozes@slackware.com>
# 27-Jan-2005
#
# Copyright 2008, 2009, 2010, 2011, 2016, 2017  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Record toolchain & other info for the build log:
slackbuildinfo

# Paths to skeleton port's source & real Slackware source tree:
export CWD=$SLACKSOURCE/$PKGSERIES/$PKGNAM
export PORTCWD=$PWD

# Temporary build locations:
export TMPBUILD=$TMP/build-$PKGNAM
export PKG=$TMP/package-$PKGNAM
mkpkgdirs # Delete & re-create temporary directories then cd into $TMPBUILD

# Extract source:
tar xvvf $CWD/$PKGNAM-$VERSION.tar.?z*
cd $PKGNAM-$VERSION || exit 1
slackhousekeeping

# Increase the default width slightly, and don't use the text
# shadow effect by default (this seems better with Pango font
# rendering):
zcat $CWD/gkrellm.theme.defaults.diff.gz | patch -p1 --verbose || failpatch

# FTBFS:
#auto_apply_patch $PORTCWD/sources/10_fix_glib_underlinkage.patch.xz || exit 1

# Fix library paths (works for all ARCHs):
sed -i -e "s#lib/gkrellm2#lib${LIBDIRSUFFIX}/gkrellm2#g" $(grep -lr 'lib/gkrellm2' *)

# Build:
make $NUMJOBS \
  CC="cc $SLKCFLAGS" \
  INSTALLROOT=/usr \
  INSTALLDIR=/usr/bin \
  INCLUDEDIR=/usr/include \
  MANDIR=/usr/man/man1 \
  LOCALEDIR=/usr/share/locale \
  PKGCONFIGDIR=/usr/lib${LIBDIRSUFFIX}/pkgconfig || \
make \
  CC="cc $SLKCFLAGS" \
  INSTALLROOT=/usr \
  INSTALLDIR=/usr/bin \
  INCLUDEDIR=/usr/include \
  MANDIR=/usr/man/man1 \
  LOCALEDIR=/usr/share/locale \
  PKGCONFIGDIR=/usr/lib${LIBDIRSUFFIX}/pkgconfig || failmake

# Install onto the file system because we need it to be installed
# before we can build the plugins:
make install
  INSTALLROOT=/usr \
  INSTALLDIR=/usr/bin \
  INCLUDEDIR=/usr/include \
  MANDIR=/usr/man/man1 \
  LOCALEDIR=/usr/share/locale \
  PKGCONFIGDIR=/usr/lib${LIBDIRSUFFIX}/pkgconfig || exit 1

# Install into the package:
make install \
  INSTALLROOT=$PKG/usr \
  INSTALLDIR=$PKG/usr/bin \
  INCLUDEDIR=$PKG/usr/include \
  MANDIR=$PKG/usr/man/man1 \
  LOCALEDIR=$PKG/usr/share/locale \
  PKGCONFIGDIR=$PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig || exit 1

# Install docs:
mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
cp -a COPYRIGHT CREDITS INSTALL README* Themes.html \
      $PKG/usr/doc/$PKGNAM-$VERSION
changelogliposuction ChangeLog $PKGNAM $VERSION

##### Build plugin ##########################################
COUNTDOWN=0.1.2

# Extract source:
cd $TMPBUILD
tar xvvf $CWD/gkrellm-countdown-$COUNTDOWN.tar.gz
cd gkrellm-countdown || exit 1
slackhousekeeping

# Build:
#sed -i 's/^FLAGS.*=\(.*\)$/FLAGS = '"$SLKCFLAGS"' \1/' Makefile
make $NUMJOBS || make || failmake

# Install into package:
mkdir -p $PKG/usr/lib/gkrellm2/plugins
install -vpm755 gkrellm-countdown.so $PKG/usr/lib${LIBDIRSUFFIX}/gkrellm2/plugins

# Install docs:
mkdir -p $PKG/usr/doc/gkrellm-countdown-$COUNTDOWN
cp -a COPYING README \
      $PKG/usr/doc/gkrellm-countdown-$COUNTDOWN
changelogliposuction ChangeLog gkrellm-countdown $COUNTDOWN

##############################################################

# If necessary, start the fakeroot server so we can set file/dir ownerships:
start_fakeroot

# Apply generic Slackware packaging policies:
cd $PKG
slackstripall   # strip all .a archives and all ELFs
slackgzpages -i # compress man & info pages and delete usr/info/dir
slackslack      # chown -R root:root, chmod -R og-w, slackchown, slack644docs
slackdesc       # install slack-desc and doinst.sh
slackmp         # run makepkg -l y -c n

# Perform any final checks on the package:
cd $PKG
slackhlinks     # search for any hard links
