#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=llvm
export VERSION=${VERSION:-4.0.1}
export BUILD=${BUILD:-2}
#export BUILD=${BUILD:-3_slack14.1}
export PKGSERIES=${PKGSERIES:-d}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps python          || installpkg $PKGSTORE/d/python-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libedit         || installpkg $PKGSTORE/l/libedit-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libxml2         || installpkg $PKGSTORE/l/libxml2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps ncurses         || installpkg $PKGSTORE/l/ncurses-[0-9]*.t?z || exit 99; }

# There's a problem with gcc-go on arm at the moment in that it seems to stall
# when the system is under load, which causes the Go test on LLVM to fail; so
# let's remove it util it works again.
removepkg gcc-go

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
