#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gnupg2
export VERSION=${VERSION:-2.1.22}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps bzip2           || installpkg $PKGSTORE/a/bzip2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps sqlite          || installpkg $PKGSTORE/ap/sqlite-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libusb          || installpkg $PKGSTORE/l/libusb-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps readline        || installpkg $PKGSTORE/l/readline-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps gnutls          || installpkg $PKGSTORE/n/gnutls-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libassuan       || installpkg $PKGSTORE/n/libassuan-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libgcrypt       || installpkg $PKGSTORE/n/libgcrypt-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libgpg-error    || installpkg $PKGSTORE/n/libgpg-error-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libksba         || installpkg $PKGSTORE/n/libksba-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps npth            || installpkg $PKGSTORE/n/npth-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps openldap-client || installpkg $PKGSTORE/n/openldap-client-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG

