#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#

source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=libwmf
export VERSION=0.2.8.4
export BUILD=1
export PKGSERIES=l
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure the package is not installed:
( cd /var/log/packages
  removepkg $PKGNAM-[0-9]*
  removepkg $PKGNAM-docs )

# Ensure build dependencies (mainly libraries):
{ slackcheckpkgdeps expat    || installpkg $PKGSTORE/l/expat-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps freetype || installpkg $PKGSTORE/l/freetype-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps glib2    || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps gtk+2    || installpkg $PKGSTORE/l/gtk+2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libjpeg-turbo  || installpkg $PKGSTORE/l/libjpeg-turbo-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng   || installpkg $PKGSTORE/l/libpng-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11   || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXau   || installpkg $PKGSTORE/x/libXau-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXdmcp || installpkg $PKGSTORE/x/libXdmcp-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxcb   || installpkg $PKGSTORE/x/libxcb-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG

# Reinstall:
ui $PKGSTORE/l/$PKGNAM-*z
