#!/bin/bash
#
# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
# Information about this package:
export PKGNAM=kernel-modules
# If it's an -rc release, remove the hyphen and rename
# the source archive.  It makes packaging and scripting all play happily.
#export VERSION=${VERSION:-4.11.0rc2next20170310}
export VERSION=${VERSION:-4.13.0rc3}

# A stable release:
# With Linux 3.x, it always has a 3 digit number - e.g. 3.2.0 rather than just 3.2:
#export VERSION=${VERSION:-4.10.0next20170224}
#export VERSION=${VERSION:-4.9.3}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-a}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
