#!/bin/bash
for ((i=0 ; i<=6 ; i++)); do
  echo "Pass: $i"
  dbuild || exit 1
  ui --reinstall ~/tgzstash/l/harfbuzz-[0-9]*.t?z
  ( cd ../freetype
     dbuild || exit 1
     ui --reinstall ~/tgzstash/l/freetype-*[0-9]*.t?z ) || exit 1
  ( cd ../pango
    dbuild || exit 1
    ui --reinstall ~/tgzstash/l/pango-*[0-9]*.t?z ) || exit 1
  ( cd ../../x/fontconfig
    dbuild || exit 1
    ui --reinstall ~/tgzstash/x/fontconfig-*[0-9]*.t?z ) || exit 1
  ( cd ../cairo
    dbuild || exit 1
    ui --reinstall ~/tgzstash/l/cairo-*[0-9]*.t?z ) || exit 1
done

echo "******* Try l/freetype/tests/compile *********"
echo "******* If breaks, try rebuilding x/fontconfig ******"
