#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=xine-ui
export VERSION=0.99.9
export BUILD=2
export PKGSERIES=xap
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps gpm         || installpkg $PKGSTORE/a/gpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps aalib       || installpkg $PKGSTORE/l/aalib-*.t?z || exit 99 ; }
{ slackcheckpkgdeps freetype    || installpkg $PKGSTORE/l/freetype-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libcaca     || installpkg $PKGSTORE/l/libcaca-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng      || installpkg $PKGSTORE/l/libpng-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses     || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }
{ slackcheckpkgdeps readline    || installpkg $PKGSTORE/l/readline-*.t?z || exit 99 ; }
{ slackcheckpkgdeps slang       || installpkg $PKGSTORE/l/slang-*.t?z || exit 99 ; }
{ slackcheckpkgdeps slang1      || installpkg $PKGSTORE/l/slang1-*.t?z || exit 99 ; }
{ slackcheckpkgdeps curl        || installpkg $PKGSTORE/n/curl-*.t?z || exit 99 ; }
{ slackcheckpkgdeps fontconfig  || installpkg $PKGSTORE/x/fontconfig-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXft      || installpkg $PKGSTORE/x/libXft-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXinerama || installpkg $PKGSTORE/x/libXinerama-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXrender  || installpkg $PKGSTORE/x/libXrender-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXtst     || installpkg $PKGSTORE/x/libXtst-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXv       || installpkg $PKGSTORE/x/libXv-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXxf86vm  || installpkg $PKGSTORE/x/libXxf86vm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps xine-lib    || installpkg $PKGSTORE/xap/xine-lib-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG 
