#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=rxvt
export VERSION=${VERSION:-2.7.10}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-xap}
#export BUILD=${BUILD:-2_slack14.2}
#export PKGSERIES=${PKGSERIES:-patches}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps libX11   || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXau   || installpkg $PKGSTORE/x/libXau-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXdmcp || installpkg $PKGSTORE/x/libXdmcp-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext  || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXpm   || installpkg $PKGSTORE/x/libXpm-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
