#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=ntp
export VERSION=${VERSION:-4.2.8p10}
export BUILD=${BUILD:-1}
#export BUILD=${BUILD:-5_slack14.1}
#export BUILD=${BUILD:-5_slack14.0}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure additional dependencies:
{ slackcheckpkgdeps libcap   || installpkg $PKGSTORE/l/libcap-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses  || installpkg $PKGSTORE/l/ncurses-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps readline || installpkg $PKGSTORE/l/readline-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps openssl  || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
