#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=alsa-utils
export VERSION=1.1.4
export BUILD=1
export PKGSERIES=ap
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure build dependencies (mainly libraries):
#slackcheckpkgdeps gpm      || installpkg $PKGSTORE/a/gpm-*.t?z
{ slackcheckpkgdeps alsa-lib        || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps fftw            || installpkg $PKGSTORE/l/fftw-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps libsamplerate   || installpkg $PKGSTORE/l/libsamplerate-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps ncurses         || installpkg $PKGSTORE/l/ncurses-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
