#!/bin/bash

# rxvt.SlackBuild
# Heavily based on the original Slackware build scripts,
# Modified by Stuart Winter <mozes@slackware.com>
# 08-May-2005

# Record toolchain & other info for the build log:
slackbuildinfo

# Paths to skeleton port's source & real Slackware source tree:
export CWD=$SLACKSOURCE/$PKGSERIES/$PKGNAM
export PORTCWD=$PWD

# Temporary build locations:
export TMPBUILD=$TMP/build-$PKGNAM
export PKG=$TMP/package-$PKGNAM
mkpkgdirs # Delete & re-create temporary directories then cd into $TMPBUILD

# Extract source:
tar xvvf $CWD/$PKGNAM-$VERSION.tar.xz
cd $PKGNAM-$VERSION || exit 1
slackhousekeeping

# Apply patches:
zcat $CWD/rxvt.utempter.diff.gz | patch -p1 --verbose --backup --suffix=.orig
# Patch for CVE-2017-7483:
zcat $CWD/rxvt-integer-overflow-fix.patch.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1

# Configure:
CFLAGS="$SLKCFLAGS" \
./configure \
   --prefix=/usr \
   --enable-languages \
   --enable-utmp \
   --enable-wtmp \
   --enable-xpm-background \
   --enable-transparency \
   --enable-menubar \
   --enable-graphics \
   --enable-rxvt-scroll \
   --enable-next-scroll \
   --enable-xterm-scroll \
   --enable-xim \
   --enable-frills \
   --enable-linespace \
   --enable-24bit \
   --enable-keepscrolling \
   --enable-mousewheel \
   --enable-slipwheeling \
   --enable-xgetdefault \
   --enable-old-selection \
   --build=${SLK_ARCH_BUILDTARGET} || failconfig

# Build:
make $NUMJOBS || make || failmake

# Install into package:
make install DESTDIR=$PKG || exit 1
rmdir $PKG/usr/lib $PKG/usr/include
rm $PKG/usr/bin/rxvt-$VERSION
mkdir -p $PKG/usr/doc/rxvt-$VERSION
cp -a \
  rxvt-$VERSION.lsm doc rclock/rclock.html \
  $PKG/usr/doc/rxvt-$VERSION
rm -r $PKG/usr/doc/rxvt-$VERSION/doc/yodl

# If necessary, start the fakeroot server so we can set file/dir ownerships:
start_fakeroot

# Apply generic Slackware packaging policies:
cd $PKG
slackstripall   # strip all .a archives and all ELFs
slackgzpages -i # compress man & info pages and delete usr/info/dir
slackslack      # chown -R root:root, chmod -R og-w, slackchown, slack644docs
slackdesc       # install slack-desc and doinst.sh
slackmp         # run makepkg -l y -c n

# Perform any final checks on the package:
cd $PKG
slackhlinks     # search for any hard links

