#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=links
export VERSION=${VERSION:-2.14}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure build dependencies (mainly libraries):
# Slackware also links against libvga but that old junk doesn't
# exist for ARM.
{ slackcheckpkgdeps bzip2   || installpkg $PKGSTORE/a/bzip2-*.t?z || exit 99 ; }
{ slackcheckpkgdeps gpm     || installpkg $PKGSTORE/a/gpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libjpeg-turbo || installpkg $PKGSTORE/l/libjpeg-turbo-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng  || installpkg $PKGSTORE/l/libpng-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libtiff || installpkg $PKGSTORE/l/libtiff-*.t?z || exit 99 ; }
#{ slackcheckpkgdeps svgalib || installpkg $PKGSTORE/l/svgalib-*.t?z || exit 99 ; }
{ slackcheckpkgdeps openssl || installpkg $PKGSTORE/n/openssl-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
