#!/bin/bash

# pcre.SlackBuild
# by Stuart Winter <mozes@slackware.com> for the Slackware porting Project.
# Heavily based on the original Slackware build script.
# 12-Jun-2004

# Record toolchain & other info for the build log:
slackbuildinfo

# Paths to skeleton port's source & real Slackware source tree:
export CWD=$SLACKSOURCE/$PKGSERIES/$PKGNAM
export PORTCWD=$PWD

# Temporary build locations:
export TMPBUILD=$TMP/build-$PKGNAM
export PKG=$TMP/package-$PKGNAM
mkpkgdirs # Delete & re-create temporary directories then cd into $TMPBUILD

# Extract source:
tar xvvf $CWD/$PKGNAM-$VERSION.tar.?z*
cd $PKGNAM-$VERSION || exit 1
slackhousekeeping

# Configure:
CFLAGS="$SLKCFLAGS" \
./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --mandir=/usr/man \
   --enable-utf8 \
   --enable-pcre16 \
   --enable-pcre32 \
   --enable-unicode-properties \
   --enable-jit \
   --enable-pcregrep-libz \
   --enable-pcregrep-libbz2 \
   --disable-static \
   --mandir=/usr/man || failconfig

# Build:
CFLAGS="$SLKCFLAGS" make $NUMJOBS || CFLAGS="$SLKCFLAGS" make || failmake

# Install into package framework:
make install DESTDIR=$PKG || failinstall
chmod 755 $PKG/usr/lib/libpcre.so.* $PKG/usr/lib/libpcreposix.so.*

# Move libraries, as they might be needed before /usr is available:
mkdir -vpm755 $PKG/lib${LIBDIRSUFFIX}
( cd $PKG/usr/lib${LIBDIRSUFFIX}
  for file in lib*.so.?.* ; do
    mv -fv $file ../../lib${LIBDIRSUFFIX}
    ln -vsf ../../lib${LIBDIRSUFFIX}/$file .
  done
  cp -fav lib*.so.? ../../lib${LIBDIRSUFFIX}
)

# Eliminate redundant docs:
rm -rf $PKG/usr/share/doc
rmdir $PKG/usr/share

# Copy docs:
mkdir -p $PKG/usr/doc/pcre-$VERSION
cp -a \
  AUTHORS COPYING* INSTALL HACKING LICENCE NEWS NON-UNIX-USE README* \
  $PKG/usr/doc/pcre-$VERSION
( cd doc ; cp -a Tech.Notes html $PKG/usr/doc/pcre-$VERSION )
changelogliposuction ChangeLog $PKGNAM $VERSION # Trim down a "ChangeLog" file

# If necessary, start the fakeroot server so we can set file/dir ownerships:
start_fakeroot

# Apply generic Slackware packaging policies:
cd $PKG
slackstripall   # strip all .a archives and all ELFs
slackgzpages -i # compress man & info pages and delete usr/info/dir
slackslack      # chown -R root:root, chmod -R og-w, slackchown, slack644docs
slackdesc       # install slack-desc and doinst.sh
slackmp         # run makepkg -l y -c n

# Perform any final checks on the package:
cd $PKG
slackhlinks     # search for any hard links
