#!/bin/bash
#
# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gpm
export VERSION=${VERSION:-1.20.7}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-a}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# For the keen eye, you'll spot a circular dependency here when
# you see that ncurses/arm/build depends on gpm.
# You don't really need ncurses to build gpm nor do you need
# gpm to build ncurses.
#slackcheckpkgdeps ncurses || installpkg $PKGSTORE/l/ncurses-*tgz
#slackcheckpkgdeps ncurses || exit 1

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
