#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=subversion
export VERSION=${VERSION:-1.9.7}
export BUILD=${BUILD:-1}
#export BUILD=${BUILD:-1_slack14.2}
export PKGSERIES=${PKGSERIES:-d}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
# This is a cirular dependency -- build neon first, then subversion then rebuild
# subversion with neon; then rebuild neon with subversion.
{ slackcheckpkgdeps neon        || installpkg $PKGSTORE/l/neon-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps dbus        || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps e2fsprogs   || installpkg $PKGSTORE/a/e2fsprogs-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps sqlite      || installpkg $PKGSTORE/ap/sqlite-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps ruby        || installpkg $PKGSTORE/d/ruby-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps apr         || installpkg $PKGSTORE/l/apr-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps apr-util    || installpkg $PKGSTORE/l/apr-util-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps db44        || installpkg $PKGSTORE/l/db44-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps expat       || installpkg $PKGSTORE/l/expat-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps qt          || installpkg $PKGSTORE/l/qt-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps cyrus-sasl  || installpkg $PKGSTORE/n/cyrus-sasl-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps openldap-client || installpkg $PKGSTORE/n/openldap-client-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps openssl     || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps httpd       || installpkg $PKGSTORE/n/httpd-[0-9]*.t?z || exit 99 ; }
#{ slackcheckpkgdeps kdelibs     || installpkg $PKGSTORE/kde/kdelibs-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
