#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gegl
export VERSION=${VERSION:-0.2.0}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps bzip2       || installpkg $PKGSTORE/a/bzip2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps atk         || installpkg $PKGSTORE/l/atk-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps babl        || installpkg $PKGSTORE/l/babl-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps cairo       || installpkg $PKGSTORE/l/cairo-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps expat       || installpkg $PKGSTORE/l/expat-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps freetype    || installpkg $PKGSTORE/l/freetype-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps glib2       || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps gtk+2       || installpkg $PKGSTORE/l/gtk+2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libgsf      || installpkg $PKGSTORE/l/libgsf-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libjpeg-turbo || installpkg $PKGSTORE/l/libjpeg-turbo-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng      || installpkg $PKGSTORE/l/libpng-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps librsvg     || installpkg $PKGSTORE/l/librsvg-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxml2     || installpkg $PKGSTORE/l/libxml2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps pango       || installpkg $PKGSTORE/l/pango-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps sdl         || installpkg $PKGSTORE/l/sdl-[0-9]*.t?z || exit 99 ; }
# Useless for ARM - we only use a dummy package here:
#{ slackcheckpkgdeps svgalib     || installpkg $PKGSTORE/l/svgalib-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps fontconfig  || installpkg $PKGSTORE/x/fontconfig-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXcursor  || installpkg $PKGSTORE/x/libXcursor-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXfixes   || installpkg $PKGSTORE/x/libXfixes-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXi       || installpkg $PKGSTORE/x/libXi-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXinerama || installpkg $PKGSTORE/x/libXinerama-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXrandr   || installpkg $PKGSTORE/x/libXrandr-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXrender  || installpkg $PKGSTORE/x/libXrender-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
