#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <stuart@armedslack.org>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=ffmpeg
export VERSION=${VERSION:-3.3.3}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps bzip2           || installpkg $PKGSTORE/a/bzip2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps xz              || installpkg $PKGSTORE/a/xz-[0-9]*.t?z      || exit 99; }
{ slackcheckpkgdeps SDL2            || installpkg $PKGSTORE/l/SDL2-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps alsa-lib        || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps freetype        || installpkg $PKGSTORE/l/freetype-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps fribidi         || installpkg $PKGSTORE/l/fribidi-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libbluray       || installpkg $PKGSTORE/l/libbluray-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libcaca         || installpkg $PKGSTORE/l/libcaca-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libcdio-paranoia || installpkg $PKGSTORE/l/libcdio-paranoia-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libssh          || installpkg $PKGSTORE/l/libssh-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libtheora       || installpkg $PKGSTORE/l/libtheora-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libvorbis       || installpkg $PKGSTORE/l/libvorbis-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libvpx          || installpkg $PKGSTORE/l/libvpx-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps ocl-icd         || installpkg $PKGSTORE/l/ocl-icd-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps pulseaudio      || installpkg $PKGSTORE/l/pulseaudio-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps v4l-utils       || installpkg $PKGSTORE/l/v4l-utils-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps wavpack         || installpkg $PKGSTORE/l/wavpack-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps gnutls          || installpkg $PKGSTORE/n/gnutls-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps samba           || installpkg $PKGSTORE/n/samba-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps fontconfig      || installpkg $PKGSTORE/x/fontconfig-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXext         || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXv           || installpkg $PKGSTORE/x/libXv-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libva           || installpkg $PKGSTORE/x/libva-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libvdpau        || installpkg $PKGSTORE/x/libvdpau-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxcb          || installpkg $PKGSTORE/x/libxcb-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps mesa            || installpkg $PKGSTORE/x/mesa-[0-9]*.t?z    || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
