#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=rsync
export VERSION=${VERSION:-3.1.2}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure additional dependencies:
{ slackcheckpkgdeps acl  || installpkg $PKGSTORE/a/acl-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps attr || installpkg $PKGSTORE/a/attr-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps popt || installpkg $PKGSTORE/l/popt-[0-9]*.t?z || exit 99 ; }

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
