#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=vim-gvim
export VERSION=${VERSION:-0.00} # dummy version - it's auto set in the SlackBuild
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-xap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM
# I also want to make sure that the latest version of ap/vim is installed.
# We need to have vim built first and available in $PKGSTORE/ap before this build
# script will work.
slackfailpkgdeps vim || removepkg vim

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps vim         || installpkg $PKGSTORE/ap/vim-*.t?z || exit 99 ; }
{ slackcheckpkgdeps acl         || installpkg $PKGSTORE/a/acl-*.t?z || exit 99 ; }
{ slackcheckpkgdeps attr        || installpkg $PKGSTORE/a/attr-*.t?z || exit 99 ; }
{ slackcheckpkgdeps gpm         || installpkg $PKGSTORE/a/gpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps atk         || installpkg $PKGSTORE/l/atk-*.t?z || exit 99 ; }
{ slackcheckpkgdeps cairo       || installpkg $PKGSTORE/l/cairo-*.t?z || exit 99 ; }
{ slackcheckpkgdeps freetype    || installpkg $PKGSTORE/l/freetype-*.t?z || exit 99 ; }
{ slackcheckpkgdeps glib2       || installpkg $PKGSTORE/l/glib2-*.t?z || exit 99 ; }
{ slackcheckpkgdeps gtk+3       || installpkg $PKGSTORE/l/gtk+3-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng      || installpkg $PKGSTORE/l/libpng-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses     || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }
{ slackcheckpkgdeps pango       || installpkg $PKGSTORE/l/pango-*.t?z || exit 99 ; }
{ slackcheckpkgdeps fontconfig  || installpkg $PKGSTORE/x/fontconfig-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libICE      || installpkg $PKGSTORE/x/libICE-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libSM       || installpkg $PKGSTORE/x/libSM-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXcursor  || installpkg $PKGSTORE/x/libXcursor-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXfixes   || installpkg $PKGSTORE/x/libXfixes-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXi       || installpkg $PKGSTORE/x/libXi-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXinerama || installpkg $PKGSTORE/x/libXinerama-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXrandr   || installpkg $PKGSTORE/x/libXrandr-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXrender  || installpkg $PKGSTORE/x/libXrender-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXt       || installpkg $PKGSTORE/x/libXt-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
