#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gphoto2
export VERSION=${VERSION:-2.5.14}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-ap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps gpm        || installpkg $PKGSTORE/a/gpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libtool    || installpkg $PKGSTORE/d/libtool-*.t?z || exit 99 ; }
{ slackcheckpkgdeps aalib      || installpkg $PKGSTORE/l/aalib-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libexif    || installpkg $PKGSTORE/l/libexif-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libgphoto2 || installpkg $PKGSTORE/l/libgphoto2-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libjpeg-turbo    || installpkg $PKGSTORE/l/libjpeg-turbo-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libusb     || installpkg $PKGSTORE/l/libusb-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses    || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }
{ slackcheckpkgdeps popt       || installpkg $PKGSTORE/l/popt-*.t?z || exit 99 ; }
{ slackcheckpkgdeps readline   || installpkg $PKGSTORE/l/readline-*.t?z || exit 99 ; }
{ slackcheckpkgdeps slang      || installpkg $PKGSTORE/l/slang-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11     || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXau     || installpkg $PKGSTORE/x/libXau-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXdmcp   || installpkg $PKGSTORE/x/libXdmcp-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxcb     || installpkg $PKGSTORE/x/libxcb-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
