#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=vim
export VERSION=${VERSION:-0.00} ## VERSION is set in the SlackBuild
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-ap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure additional dependencies:
{ slackcheckpkgdeps acl     || installpkg $PKGSTORE/a/acl-*.t?z || exit 99 ; }
{ slackcheckpkgdeps attr    || installpkg $PKGSTORE/a/attr-*.t?z || exit 99 ; }
{ slackcheckpkgdeps gpm     || installpkg $PKGSTORE/a/gpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
