#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=iptables
export VERSION=${VERSION:-1.6.1}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz


# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure run-time dependencies are installed:
{ slackcheckpkgdeps libpcap         || installpkg $PKGSTORE/l/libpcap-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libnetfilter_conntrack || installpkg $PKGSTORE/n/libnetfilter_conntrack-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libnfnetlink    || installpkg $PKGSTORE/n/libnfnetlink-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
