#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=lvm2
export VERSION=${VERSION:-2.02.173}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-a}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
# DO NOT REMOVE otherwise the system starts falling over!
# slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure pre-requisite packages are installed:
#slackcheckpkgdeps device-mapper || installpkg $PKGSTORE/a/device-mapper*-*.t?z
{ slackcheckpkgdeps eudev || installpkg $PKGSTORE/a/eudev-[0-9]*.t?z    || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
