#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=xine-lib
export VERSION=${VERSION:-1.2.8}
export BUILD=${BUILD:-3}
export PKGSERIES=${PKGSERIES:-xap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps bzip2           || installpkg $PKGSTORE/a/bzip2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps gpm             || installpkg $PKGSTORE/a/gpm-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps xz              || installpkg $PKGSTORE/a/xz-[0-9]*.t?z      || exit 99; }
{ slackcheckpkgdeps flac            || installpkg $PKGSTORE/ap/flac-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps a52dec          || installpkg $PKGSTORE/l/a52dec-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps aalib           || installpkg $PKGSTORE/l/aalib-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps alsa-lib        || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps esound          || installpkg $PKGSTORE/l/esound-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps gdk-pixbuf2     || installpkg $PKGSTORE/l/gdk-pixbuf2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libcaca         || installpkg $PKGSTORE/l/libcaca-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libdvdnav       || installpkg $PKGSTORE/l/libdvdnav-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libdvdread      || installpkg $PKGSTORE/l/libdvdread-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libjpeg-turbo   || installpkg $PKGSTORE/l/libjpeg-turbo-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libmad          || installpkg $PKGSTORE/l/libmad-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libmng          || installpkg $PKGSTORE/l/libmng-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libogg          || installpkg $PKGSTORE/l/libogg-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libtheora       || installpkg $PKGSTORE/l/libtheora-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libvorbis       || installpkg $PKGSTORE/l/libvorbis-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libvpx          || installpkg $PKGSTORE/l/libvpx-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps pulseaudio      || installpkg $PKGSTORE/l/pulseaudio-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps sdl             || installpkg $PKGSTORE/l/sdl-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps slang1          || installpkg $PKGSTORE/l/slang1-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps v4l-utils       || installpkg $PKGSTORE/l/v4l-utils-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps wavpack         || installpkg $PKGSTORE/l/wavpack-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps samba           || installpkg $PKGSTORE/n/samba-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps glu             || installpkg $PKGSTORE/x/glu-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps libICE          || installpkg $PKGSTORE/x/libICE-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libSM           || installpkg $PKGSTORE/x/libSM-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXext         || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXinerama     || installpkg $PKGSTORE/x/libXinerama-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXv           || installpkg $PKGSTORE/x/libXv-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libXvMC         || installpkg $PKGSTORE/x/libXvMC-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libva           || installpkg $PKGSTORE/x/libva-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libvdpau        || installpkg $PKGSTORE/x/libvdpau-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxcb          || installpkg $PKGSTORE/x/libxcb-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps mesa            || installpkg $PKGSTORE/x/mesa-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps imagemagick     || installpkg $PKGSTORE/l/imagemagick-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
