#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=crda
export VERSION=${VERSION:-3.18}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps libnl3       || installpkg $PKGSTORE/l/libnl3-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps M2Crypto     || installpkg $PKGSTORE/l/M2Crypto-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libgcrypt    || installpkg $PKGSTORE/n/libgcrypt-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libnl        || installpkg $PKGSTORE/l/libnl-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libgpg-error || installpkg $PKGSTORE/n/libgpg-error-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps M2Crypto     || installpkg $PKGSTORE/l/M2Crypto-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
