#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=libcdio
export VERSION=0.94
export BUILD=2
export PKGSERIES=l
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
# This package links against l/libcddb but will also build
# without support for it.
# When first building, you need to build in this order:
# 1. Build & install this package
# 2. Build & install l/libcddb
# 3. Rebuild & reinstall this package
# 
{ slackcheckpkgdeps libcddb || installpkg $PKGSTORE/l/libcddb-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
