#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gvfs
export VERSION=${VERSION:-1.32.1}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps acl             || installpkg $PKGSTORE/a/acl-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps attr            || installpkg $PKGSTORE/a/attr-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps bzip2           || installpkg $PKGSTORE/a/bzip2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps dbus            || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps eudev            || installpkg $PKGSTORE/a/eudev-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps udisks2         || installpkg $PKGSTORE/a/udisks2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps xz              || installpkg $PKGSTORE/a/xz-[0-9]*.t?z      || exit 99; }
{ slackcheckpkgdeps libtool         || installpkg $PKGSTORE/d/libtool-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps dbus-glib       || installpkg $PKGSTORE/l/dbus-glib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps expat           || installpkg $PKGSTORE/l/expat-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps fuse            || installpkg $PKGSTORE/l/fuse-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libarchive      || installpkg $PKGSTORE/l/libarchive-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libcdio         || installpkg $PKGSTORE/l/libcdio-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libexif         || installpkg $PKGSTORE/l/libexif-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libgnome-keyring || installpkg $PKGSTORE/l/libgnome-keyring-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libgphoto2      || installpkg $PKGSTORE/l/libgphoto2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libsoup         || installpkg $PKGSTORE/l/libsoup-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxml2         || installpkg $PKGSTORE/l/libxml2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps bluez           || installpkg $PKGSTORE/n/bluez-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libgcrypt       || installpkg $PKGSTORE/n/libgcrypt-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libgpg-error    || installpkg $PKGSTORE/n/libgpg-error-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps openssl         || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps samba           || installpkg $PKGSTORE/n/samba-[0-9]*.t?z   || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
