#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=libcddb
export VERSION=1.3.2
export BUILD=1
export PKGSERIES=l
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
#export PKGSTORE=/tmp/
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
# This package, 'libcddb' & l/libcdio link against each other.
# So you need to, in this order:
# 
# 1. build l/libcdio first without l/libcddb (this package),
# 2. build & install this package;
# 3. once again rebuild l/libcdio
#
{ slackcheckpkgdeps libcdio || installpkg $PKGSTORE/l/libcdio-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
