#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gd
export VERSION=${VERSION:-2.2.4}
export BUILD=${BUILD:-1}
#export BUILD=${BUILD:-1_slack14.2}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps expat      || installpkg $PKGSTORE/l/expat-*.t?z || exit 99 ; }
{ slackcheckpkgdeps freetype   || installpkg $PKGSTORE/l/freetype-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libjpeg-turbo    || installpkg $PKGSTORE/l/libjpeg-turbo-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng     || installpkg $PKGSTORE/l/libpng-*.t?z || exit 99 ; }
{ slackcheckpkgdeps fontconfig || installpkg $PKGSTORE/x/fontconfig-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11     || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXau     || installpkg $PKGSTORE/x/libXau-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXdmcp   || installpkg $PKGSTORE/x/libXdmcp-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext    || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXpm     || installpkg $PKGSTORE/x/libXpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxcb     || installpkg $PKGSTORE/x/libxcb-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG

