#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=clisp
export VERSION=${VERSION:-2.49.20161111hg}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-d}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed otherwise
# newer clisp uses older installed clisp to generate stuff which then breaks.
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure package dependencies are installed:
{ slackcheckpkgdeps libsigsegv  || installpkg $PKGSTORE/l/libsigsegv-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses  || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }
{ slackcheckpkgdeps pcre     || installpkg $PKGSTORE/l/pcre-*.t?z || exit 99 ; }
{ slackcheckpkgdeps readline || installpkg $PKGSTORE/l/readline-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libICE   || installpkg $PKGSTORE/x/libICE-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libSM    || installpkg $PKGSTORE/x/libSM-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11   || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext  || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXpm   || installpkg $PKGSTORE/x/libXpm-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
