#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=ruby
export VERSION=${VERSION:-2.4.1} # hyphens taken care of in the build script
export BUILD=${BUILD:-1}
#export BUILD=${BUILD:-1_slack14.0}
export PKGSERIES=${PKGSERIES:-d}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# You may wonder how I know which version numbers I'm dealing with.
# The answer is that at present present I do not need to worry.
# For different versions of ARMedslack I chroot into that version 
# and build using only the packages built for that version.
#
# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps db48            || installpkg $PKGSTORE/l/db48-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps gdbm            || installpkg $PKGSTORE/l/gdbm-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps gmp             || installpkg $PKGSTORE/l/gmp-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libyaml         || installpkg $PKGSTORE/l/libyaml-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps ncurses         || installpkg $PKGSTORE/l/ncurses-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps readline        || installpkg $PKGSTORE/l/readline-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps openssl         || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
