#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=xmms
export VERSION=${VERSION:-1.2.11}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-xap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps e2fsprogs   || installpkg $PKGSTORE/a/e2fsprogs-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps alsa-lib    || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps audiofile   || installpkg $PKGSTORE/l/audiofile-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps esound      || installpkg $PKGSTORE/l/esound-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps glib        || installpkg $PKGSTORE/l/glib-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps gtk+        || installpkg $PKGSTORE/l/gtk+-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libogg      || installpkg $PKGSTORE/l/libogg-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libvorbis   || installpkg $PKGSTORE/l/libvorbis-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libICE      || installpkg $PKGSTORE/x/libICE-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libSM       || installpkg $PKGSTORE/x/libSM-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXxf86vm  || installpkg $PKGSTORE/x/libXxf86vm-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps mesa        || installpkg $PKGSTORE/x/mesa-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
