#!/bin/bash
# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=openssh
export VERSION=${VERSION:-7.5p1}
export BUILD=${BUILD:-2}
#export BUILD=${BUILD:-1_slack14.2}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure specific build dependencies (mainly libraries):
# We'll need some other bits from the old tcpip package --
# I haven't worked out what they are now that the package has
# been split up.
#slackcheckpkgdeps tcpip   || installpkg $PKGSTORE/n/tcpip-*.tgz
{ slackcheckpkgdeps openssl || installpkg $PKGSTORE/n/openssl-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG

