#!/bin/bash

source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=netpbm
export VERSION=10.66.02
export BUILD=1
export PKGSERIES=l
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure build dependencies:
# Also depends on l/svgalib but this is does not exist for ARM.
# However, ARMedslack now uses the svgalib-dummy package from Debian.
{ slackcheckpkgdeps libjpeg-turbo || installpkg $PKGSTORE/l/libjpeg-turbo-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libpng  || installpkg $PKGSTORE/l/libpng-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libtiff || installpkg $PKGSTORE/l/libtiff-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libxml2 || installpkg $PKGSTORE/l/libxml2-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps svgalib || installpkg $PKGSTORE/l/svgalib-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11  || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG 
