#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=hplip
export VERSION=${VERSION:-3.17.7}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-ap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
#
# This one won't show in ldd but is a dependency.
{ slackcheckpkgdeps icu4c       || installpkg $PKGSTORE/l/icu4c-[0-9]*.t?z || exit 99 ; }
#
{ slackcheckpkgdeps dbus            || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps cups            || installpkg $PKGSTORE/ap/cups-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libjpeg-turbo   || installpkg $PKGSTORE/l/libjpeg-turbo-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libusb          || installpkg $PKGSTORE/l/libusb-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps net-snmp        || installpkg $PKGSTORE/n/net-snmp-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps openssl         || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps sane            || installpkg $PKGSTORE/xap/sane-[0-9]*.t?z  || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
