#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=nmap
export VERSION=${VERSION:-7.60}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-n}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure build dependencies:
# nmapfe is the X front end and requires these things:
# Slackware 13.0 doesn't link against these.
#{ slackcheckpkgdeps atk || installpkg $PKGSTORE/l/atk-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps cairo       || installpkg $PKGSTORE/l/cairo-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps freetype    || installpkg $PKGSTORE/l/freetype-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps glib2       || installpkg $PKGSTORE/l/glib2-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps gtk+2       || installpkg $PKGSTORE/l/gtk+2-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libpng      || installpkg $PKGSTORE/l/libpng-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps pango       || installpkg $PKGSTORE/l/pango-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps pcre        || installpkg $PKGSTORE/l/pcre-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps openssl     || installpkg $PKGSTORE/n/openssl-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps fontconfig  || installpkg $PKGSTORE/x/fontconfig-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXcursor  || installpkg $PKGSTORE/x/libXcursor-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXfixes   || installpkg $PKGSTORE/x/libXfixes-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXi       || installpkg $PKGSTORE/x/libXi-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXinerama || installpkg $PKGSTORE/x/libXinerama-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXrandr   || installpkg $PKGSTORE/x/libXrandr-*.tgz || exit 99 ; }
#{ slackcheckpkgdeps libXrender  || installpkg $PKGSTORE/x/libXrender-*.tgz || exit 99 ; }
#
{ slackcheckpkgdeps pcre        || installpkg $PKGSTORE/l/pcre-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps openssl     || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
