#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=calligra-l10n ### unused for PACKAGES but used to get the dir name in the slackware x86 tree
export VERSION=${VERSION:-2.9.11} ## this is Calligra's version not KDE's
export PKGARCH=noarch # Override defaults from the slackkit config
export BUILD=1
export PKGSERIES=${PKGSERIES:-kdei}

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
# Ensure all of KDE is installed.

# If we specified anything to $1 then it means that we only want to
# build one particular package.
[ ! -z "$1" ] && export PKGLANG=$1

# Launch the package build script:
BUILDLOG=$PKGNAM.build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
