#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=audacious-plugins
export VERSION=${VERSION:-3.8.2}
export BUILD=${BUILD:-3}
export PKGSERIES=${PKGSERIES:-xap}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps dbus            || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps flac            || installpkg $PKGSTORE/ap/flac-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps mpg123          || installpkg $PKGSTORE/ap/mpg123-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps SDL2            || installpkg $PKGSTORE/l/SDL2-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps alsa-lib        || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps atk             || installpkg $PKGSTORE/l/atk-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps cairo           || installpkg $PKGSTORE/l/cairo-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps dbus-glib       || installpkg $PKGSTORE/l/dbus-glib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps ffmpeg          || installpkg $PKGSTORE/l/ffmpeg-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps freetype        || installpkg $PKGSTORE/l/freetype-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps gdk-pixbuf2     || installpkg $PKGSTORE/l/gdk-pixbuf2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps gtk+2           || installpkg $PKGSTORE/l/gtk+2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libcddb         || installpkg $PKGSTORE/l/libcddb-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libcdio         || installpkg $PKGSTORE/l/libcdio-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libcdio-paranoia || installpkg $PKGSTORE/l/libcdio-paranoia-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libnotify       || installpkg $PKGSTORE/l/libnotify-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libogg          || installpkg $PKGSTORE/l/libogg-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libsamplerate   || installpkg $PKGSTORE/l/libsamplerate-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libsndfile      || installpkg $PKGSTORE/l/libsndfile-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libvorbis       || installpkg $PKGSTORE/l/libvorbis-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxml2         || installpkg $PKGSTORE/l/libxml2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps neon            || installpkg $PKGSTORE/l/neon-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps pango           || installpkg $PKGSTORE/l/pango-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps pulseaudio      || installpkg $PKGSTORE/l/pulseaudio-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps wavpack         || installpkg $PKGSTORE/l/wavpack-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps curl            || installpkg $PKGSTORE/n/curl-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps fontconfig      || installpkg $PKGSTORE/x/fontconfig-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXcomposite   || installpkg $PKGSTORE/x/libXcomposite-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXrender      || installpkg $PKGSTORE/x/libXrender-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps mesa            || installpkg $PKGSTORE/x/mesa-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps audacious       || installpkg $PKGSTORE/xap/audacious-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
