#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <stuart@armedslack.org>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=pulseaudio
export VERSION=${VERSION:-10.0}
export BUILD=${BUILD:-1}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps dbus            || installpkg $PKGSTORE/a/dbus-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps eudev           || installpkg $PKGSTORE/a/eudev-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps util-linux      || installpkg $PKGSTORE/a/util-linux-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps flac            || installpkg $PKGSTORE/ap/flac-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libtool         || installpkg $PKGSTORE/d/libtool-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps GConf           || installpkg $PKGSTORE/l/GConf-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps alsa-lib        || installpkg $PKGSTORE/l/alsa-lib-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps fftw            || installpkg $PKGSTORE/l/fftw-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libasyncns      || installpkg $PKGSTORE/l/libasyncns-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libcap          || installpkg $PKGSTORE/l/libcap-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libogg          || installpkg $PKGSTORE/l/libogg-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libsndfile      || installpkg $PKGSTORE/l/libsndfile-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libvorbis       || installpkg $PKGSTORE/l/libvorbis-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps orc             || installpkg $PKGSTORE/l/orc-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps sbc             || installpkg $PKGSTORE/l/sbc-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps speexdsp        || installpkg $PKGSTORE/l/speexdsp-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps openssl         || installpkg $PKGSTORE/n/openssl-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps samba           || installpkg $PKGSTORE/n/samba-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libICE          || installpkg $PKGSTORE/x/libICE-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libSM           || installpkg $PKGSTORE/x/libSM-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libX11          || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXau          || installpkg $PKGSTORE/x/libXau-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libXdmcp        || installpkg $PKGSTORE/x/libXdmcp-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXext         || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libXi           || installpkg $PKGSTORE/x/libXi-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps libXtst         || installpkg $PKGSTORE/x/libXtst-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libxcb          || installpkg $PKGSTORE/x/libxcb-[0-9]*.t?z  || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
