#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=parted
export VERSION=${VERSION:-3.2}
export BUILD=${BUILD:-3}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
# 10-Feb-2010:
#
# It used to require devicemapper but this has been wound into the lvm2 package now.
{ slackcheckpkgdeps lvm2          || installpkg $PKGSTORE/a/lvm2-*.t?z || exit 99 ; }
{ slackcheckpkgdeps e2fsprogs     || installpkg $PKGSTORE/a/e2fsprogs-*.t?z || exit 99 ; }
{ slackcheckpkgdeps ncurses       || installpkg $PKGSTORE/l/ncurses-*.t?z || exit 99 ; }
{ slackcheckpkgdeps readline      || installpkg $PKGSTORE/l/readline-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
