#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=xgames
export VERSION=0.3
export BUILD=1
export PKGSERIES=xap
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps libICE  || installpkg $PKGSTORE/x/libICE-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libSM   || installpkg $PKGSTORE/x/libSM-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11  || installpkg $PKGSTORE/x/libX11-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext || installpkg $PKGSTORE/x/libXext-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXmu  || installpkg $PKGSTORE/x/libXmu-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXp   || installpkg $PKGSTORE/x/libXp-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXpm  || installpkg $PKGSTORE/x/libXpm-*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXt   || installpkg $PKGSTORE/x/libXt-*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG 
