#!/bin/bash

# lha.SlackBuild
# Heavily based on the original Slackware build scripts,
# Modified by Stuart Winter <mozes@slackware.com>

# Record toolchain & other info for the build log:
slackbuildinfo

# Paths to skeleton port's source & real Slackware source tree:
export CWD=$SLACKSOURCE/$PKGSERIES/$PKGNAM
export PORTCWD=$PWD

# Temporary build locations:
export TMPBUILD=$TMP/build-$PKGNAM
export PKG=$TMP/package-$PKGNAM
mkpkgdirs # Delete & re-create temporary directories then cd into $TMPBUILD

# Extract source:
tar xvvf $CWD/$PKGNAM-$VERSION.tar.gz
cd $PKGNAM-$VERSION || exit 1
slackhousekeeping

# Apply patches:
zcat $CWD/lha_1.14i-10.1.diff.gz | patch -p1 --verbose || exit 1
patch -p0 < debian/patch.paul
patch -p0 < debian/patch.multibyte
patch -p0 < debian/patch.CAN-2004-0234_0235
patch -p0 < debian/patch.header-overflow
patch -p1 < debian/patch.redhat-sec2
patch -p1 < debian/patch.CVE-2006-4335-CVE-2006-4337-CVE-2006-4338

# Build:
sed -i 's/^OPTIMIZE\t=\(.*\)$/OPTIMIZE = '"$SLKCFLAGS"' \1/' Makefile
make $NUMJOBS || make || failmake

# Install into package:
mkdir -p $PKG/usr/{bin,/man/man1,man/jp/man1}
install -m755 src/lha $PKG/usr/bin
install -m644 debian/lha.1 $PKG/usr/man/man1
install -m644 man/lha.man $PKG/usr/man/jp/man1/lha.1

# Copy docs:
mkdir -pm755 $PKG/usr/doc/$PKGNAM-$VERSION/jp
cp -favv change-${VERSION}.txt \
         $PKG/usr/doc/$PKGNAM-${VERSION}
cp -favv *.euc \
         $PKG/usr/doc/$PKGNAM-${VERSION}/jp

# If necessary, start the fakeroot server so we can set file/dir ownerships:
start_fakeroot

# Apply generic Slackware packaging policies:
cd $PKG
slackstripall   # strip all .a archives and all ELFs
slackgzpages -i # compress man & info pages and delete usr/info/dir
slackslack      # chown -R root:root, chmod -R og-w, slackchown, slack644docs
slackdesc       # install slack-desc and doinst.sh
slackmp         # run makepkg -l y -c n

# Perform any final checks on the package:
cd $PKG
slackhlinks     # search for any hard links
