#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=glib-networking
export VERSION=${VERSION:-2.50.0}
export BUILD=${BUILD:-2}
export PKGSERIES=${PKGSERIES:-l}
export SLACKPACKAGE=$PKGNAM-$VERSION-$PKGARCH-$BUILD.txz

## ******************************************************************* ##
# For test packages - best to store in another location rather than
# overwriting the working copy in the main tree:
# export PKGSTORE=/tmp/
# mkdir -vpm755 $PKGSTORE/$PKGSERIES
## ******************************************************************* ##

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure $PKGNAM isn't already installed:
slackfailpkgdeps $PKGNAM || removepkg $PKGNAM

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps util-linux      || installpkg $PKGSTORE/a/util-linux-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps glib2           || installpkg $PKGSTORE/l/glib2-[0-9]*.t?z   || exit 99; }
{ slackcheckpkgdeps gmp             || installpkg $PKGSTORE/l/gmp-[0-9]*.t?z     || exit 99; }
{ slackcheckpkgdeps libffi          || installpkg $PKGSTORE/l/libffi-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps libidn2         || installpkg $PKGSTORE/l/libidn2-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libproxy        || installpkg $PKGSTORE/l/libproxy-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps libunistring    || installpkg $PKGSTORE/l/libunistring-[0-9]*.t?z || exit 99; }
{ slackcheckpkgdeps pcre            || installpkg $PKGSTORE/l/pcre-[0-9]*.t?z    || exit 99; }
{ slackcheckpkgdeps gnutls          || installpkg $PKGSTORE/n/gnutls-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps nettle          || installpkg $PKGSTORE/n/nettle-[0-9]*.t?z  || exit 99; }
{ slackcheckpkgdeps p11-kit         || installpkg $PKGSTORE/n/p11-kit-[0-9]*.t?z || exit 99; }
# If the build fails due to a missing ca-certs, reinstall this package:
removepkg ca-certificates
{ slackcheckpkgdeps ca-certificates || installpkg $PKGSTORE/n/ca-certificates-[0-9]*.t?z || exit 99; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG
