#!/bin/bash

# arm/build
# Check package dependencies, set metadata and launch
# package build script.
# by Stuart Winter <mozes@slackware.com>
#
source /usr/share/slackdev/buildkit.sh

# Package metadata:
export PKGNAM=gtk+
export VERSION=1.2.10
export BUILD=1
export PKGSERIES=l
export SLACKPACKAGE=$PKGNAM-$VERSION-$ARCH-$BUILD.txz

# Reset the ARM file system: restore it to the 'factory settings'
# as it were (this has no effect when building natively):
sboxsysrestore

# Ensure base ARM packages are installed first:
slackbasedeps

# Ensure specific build dependencies (mainly libraries):
{ slackcheckpkgdeps glib        || installpkg $PKGSTORE/l/glib-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libX11      || installpkg $PKGSTORE/x/libX11-[0-9]*.t?z || exit 99 ; }
{ slackcheckpkgdeps libXext     || installpkg $PKGSTORE/x/libXext-[0-9]*.t?z || exit 99 ; }

# Launch the package build script:
BUILDLOG=$( basename $SLACKPACKAGE .t?z ).build.log
( ./$PKGNAM.SlackBuild ) >& /dev/stdout | tee $BUILDLOG

# Compress the build log:
bzip2 -9fvz $BUILDLOG

